### ISSUE TITLE
Unable to "python run.py"

### ISSUE THREAD

**Issue by hydropero** [DevOpsBootcamp/Bootcamp-Exercises#21]
While attempting to python run.py in a virtual environment I get 

`ModuleNotFoundError: No module named 'guest' `

The full error:
`Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/mbulla/Bootcamp-Exercises/frameworks/app/__init__.py", line 9, in <module>
    from app.models import Guest
  File "/home/mbulla/Bootcamp-Exercises/frameworks/app/models/__init__.py", line 1, in <module>
    from guest import Guest
ModuleNotFoundError: No module named 'guest'`

**Comment by hydropero** [comment]
Nevermind, I believe everything was written with Python2 and that's why I am unable to follow this project myself.

**Comment by ramereth** [comment]
Yes, we unfortunately haven't updated this for Python3 yet. Feel free to make a PR which updates it!

**Comment by yehtetmaungmaung** [comment]
Hello guys. I'm also learning with OSU DOBC. First I installed python2 on global using ..
   $sudo apt install python2
Then I installed python2 in virtualenv using..
   $virtualenv --python=/usr/bin/python2 venv
It shows some warning but I think it's okay as we are learning.
